//! SNAP (SCTP Negotiation Acceleration Protocol) types.
//!
//! See [draft-hancke-tsvwg-snap](https://datatracker.ietf.org/doc/draft-hancke-tsvwg-snap/).

use std::sync::Arc;

use base64ct::{Base64, Encoding};
use sctp_proto::{ClientConfig, TransportConfig, generate_snap_token};

use super::SctpError as Error;

/// Build the WebRTC transport config with unlimited retransmits.
///
/// For WebRTC, we never want to give up retransmitting init and data packets.
/// The connectivity is in ICE, and SCTP should not give up until ICE gives up.
pub(super) fn webrtc_transport_config(max_message_size: u32) -> Arc<TransportConfig> {
    Arc::new(
        TransportConfig::default()
            .with_max_init_retransmits(None)
            .with_max_data_retransmits(None)
            .with_max_send_message_size(max_message_size)
            .with_max_receive_message_size(max_message_size),
    )
}

/// Out-of-band SCTP INIT data for SNAP negotiation.
///
/// Holds the local and remote SCTP INIT chunks exchanged via signaling
/// (e.g. SDP `a=sctp-init`). When both are present, the SCTP association
/// skips the 4-way handshake and goes directly to established state.
///
/// Typical flow:
///
/// 1. Create `SctpInitData`.
/// 2. Call [`Self::local_init_chunk()`] and signal the returned bytes.
/// 3. Receive the peer's INIT bytes over signaling.
/// 4. Call [`Self::set_remote_init_chunk()`].
/// 5. Pass the populated value to
///    [`DirectApi::start_sctp_with_snap()`][crate::change::DirectApi::start_sctp_with_snap].
///
/// The local INIT chunk is lazily generated and cached on first access.
///
/// # Example
/// ```
/// # use str0m::sctp::SctpInitData;
///
/// let mut data = SctpInitData::new(262144);
///
/// // Get local INIT chunk to send to remote peer
/// let local_init = data.local_init_chunk().expect("valid chunk");
///
/// // Later, set the remote INIT chunk received from peer
/// // data.set_remote_init_chunk(remote_init_bytes);
/// ```
#[derive(Debug, Clone)]
pub struct SctpInitData {
    pub(crate) transport: Arc<TransportConfig>,
    pub(crate) local_init: Option<Vec<u8>>,
    pub(crate) remote_init: Option<Vec<u8>>,
}

impl SctpInitData {
    /// Creates new default SCTP INIT data.
    ///
    /// By default, max init and data retransmits are set to `None` (unlimited),
    /// which is recommended for WebRTC where connectivity is managed by ICE.
    pub fn new(max_message_size: u32) -> Self {
        SctpInitData {
            transport: webrtc_transport_config(max_message_size),
            local_init: None,
            remote_init: None,
        }
    }

    /// Get the local INIT chunk bytes for out-of-band signaling.
    ///
    /// This generates a fresh INIT chunk using the transport config parameters.
    /// The result can be exchanged with the remote peer via a signaling channel,
    /// allowing both sides to skip the SCTP 4-way handshake.
    ///
    /// The generated bytes are cached so subsequent calls return the same INIT.
    ///
    /// If you plan to call `start_sctp_with_snap()`, call this method first so
    /// the local INIT is captured in the `SctpInitData` you pass in.
    pub fn local_init_chunk(&mut self) -> Result<Vec<u8>, Error> {
        if let Some(init) = &self.local_init {
            return Ok(init.clone());
        }
        let init = generate_snap_token(&self.transport)?.to_vec();
        self.local_init = Some(init.clone());
        Ok(init)
    }

    /// Get the local INIT chunk as a base64-encoded string for out-of-band signaling.
    ///
    /// This generates a fresh INIT chunk using the transport config parameters.
    /// The result can be exchanged with the remote peer via a signaling channel,
    /// allowing both sides to skip the SCTP 4-way handshake.
    ///
    /// The generated bytes are cached so subsequent calls return the same string.
    ///
    /// If you plan to call `start_sctp_with_snap()`, call this method first so
    /// the local INIT is captured in the `SctpInitData` you pass in.
    pub fn local_init_chunk_string(&mut self) -> Result<String, Error> {
        let b = self.local_init_chunk()?;
        Ok(Base64::encode_string(&b))
    }

    /// Set the remote INIT chunk.
    pub fn set_remote_init_chunk(&mut self, bytes: Vec<u8>) {
        self.remote_init = Some(bytes);
    }

    /// Set the remote INIT chunk from a base64 string.
    pub fn set_remote_init_string(&mut self, s: &str) -> Result<(), Error> {
        let b = Base64::decode_vec(s).map_err(|e| Error::Proto(sctp_proto::Error::Other(format!("{:?}", e))))?;
        self.set_remote_init_chunk(b);
        Ok(())
    }

    /// Get the remote INIT chunk as a base64 string, if set.
    pub fn remote_init_string(&self) -> Option<String> {
        self.remote_init.as_ref().map(|b| Base64::encode_string(b))
    }

    /// Return the config for a client association based on these init chunks.
    pub(crate) fn into_client_config(self) -> ClientConfig {
        let mut config = ClientConfig::new();
        config.transport = self.transport;
        if let (Some(local), Some(remote)) = (self.local_init, self.remote_init) {
            config = config.with_snap(local.into(), remote.into());
        }
        config
    }

    /// Get local INIT chunk for signaling.
    pub fn local_init_chunk_bytes(&self) -> Option<&[u8]> {
        self.local_init.as_deref()
    }
}

pub(crate) fn b64_encode(b: &[u8]) -> String {
    Base64::encode_string(b)
}
